// AUTO-GENERATED by scripts/fetch-anthropic-pricing.mjs. Do not edit by hand.
// Source: OpenRouter /api/v1/models (pass-through Anthropic rates).
// Fetched: 2026-07-12T16:18:28.942Z

export type ModelRate = { input: number; output: number };

export const PRICING_FETCHED_AT = "2026-07-12T16:18:28.942Z";
export const PRICING_SOURCE = "openrouter:/api/v1/models";

// USD per million tokens. Keyed by both dashed (Anthropic API) and
// dotted (OpenRouter) model ids so either string resolves.
export const MODEL_PRICING: Record<string, ModelRate> = {
  "claude-sonnet-5": {
    "input": 2,
    "output": 10
  },
  "claude-fable-5": {
    "input": 10,
    "output": 50
  },
  "claude-opus-4-8-fast": {
    "input": 10,
    "output": 50
  },
  "claude-opus-4.8-fast": {
    "input": 10,
    "output": 50
  },
  "claude-opus-4-8": {
    "input": 5,
    "output": 25
  },
  "claude-opus-4.8": {
    "input": 5,
    "output": 25
  },
  "claude-opus-4-7-fast": {
    "input": 30,
    "output": 150
  },
  "claude-opus-4.7-fast": {
    "input": 30,
    "output": 150
  },
  "claude-opus-4-7": {
    "input": 5,
    "output": 25
  },
  "claude-opus-4.7": {
    "input": 5,
    "output": 25
  },
  "claude-sonnet-4-6": {
    "input": 3,
    "output": 15
  },
  "claude-sonnet-4.6": {
    "input": 3,
    "output": 15
  },
  "claude-opus-4-6": {
    "input": 5,
    "output": 25
  },
  "claude-opus-4.6": {
    "input": 5,
    "output": 25
  },
  "claude-opus-4-5": {
    "input": 5,
    "output": 25
  },
  "claude-opus-4.5": {
    "input": 5,
    "output": 25
  },
  "claude-haiku-4-5": {
    "input": 1,
    "output": 5
  },
  "claude-haiku-4.5": {
    "input": 1,
    "output": 5
  },
  "claude-sonnet-4-5": {
    "input": 3,
    "output": 15
  },
  "claude-sonnet-4.5": {
    "input": 3,
    "output": 15
  },
  "claude-opus-4-1": {
    "input": 15,
    "output": 75
  },
  "claude-opus-4.1": {
    "input": 15,
    "output": 75
  },
  "claude-opus-4": {
    "input": 15,
    "output": 75
  },
  "claude-sonnet-4": {
    "input": 3,
    "output": 15
  },
  "claude-3-haiku": {
    "input": 0.25,
    "output": 1.25
  }
};
